arch: s390x
services:
  - docker
script: docker login quay.io -u $ROBOT -p $ROBOT_TOKEN && docker build s390x/jdk/ubuntu12.04 --tag quay.io/ibmz/openjdk:11.0.8 && ls s390x/test && docker push quay.io/ibmz/openjdk
