arch: s390x
services:
  - docker
script: docker login quay.io -u $ROBOT -p $ROBOT_TOKEN && docker build s390x/jdk/alpine3.11/Dockerfile --tag quay.io/repository/lcarcaramo/openjkd:11.0.8+10 && docker push https://quay.io/repository/lcarcaramo/openjkd
