arch: s390x
language: bash
services:
  - docker
script: docker login quay.io -u $ROBOT -p $ROBOT_TOKEN && docker build s390x/jdk/ubuntu12.04 --tag quay.io/ibmz/openjdk:11.0.8 && bash s390x/test/jdk/ubuntu12.04/test.sh && docker push quay.io/ibmz/openjdk
